### ISSUE TITLE
用jacquard数据集训练的问题

### ISSUE THREAD

**Issue by zehub123** [OranHe/Rgbd-GG-CNN#1]
大佬您好，您的算法可以用来训练cornell数据集吗？我试了一下，报了很多错误，还没有改完。请问您用训练jacquard数据集时，只需要把train.py文件中的OranDataset改为JacquardDataset就可以吗？还是需要改其他地方才可以训练。提前感谢您的解答

**Comment by OranHe** [comment]
你好 這個項目是在https://github.com/dougsm/ggcnn 基礎上再做修改的，可以先嘗試在ggcnn上面跑通（無需修改代碼），再引入我模型的架構可能比較好理解。我的這個項目可以在CornellDataset和JacquardDataset上跑，我有做過相應的訓練實驗。也可以把報錯信息發過來，我幫忙看下，我目前是覺得主要是網絡架構不同產生的報錯吧。

**Comment by zehub123** [comment]
> 你好 這個項目是在https://github.com/dougsm/ggcnn 基礎上再做修改的，可以先嘗試在ggcnn上面跑通（無需修改代碼），再引入我模型的架構可能比較好理解。我的這個項目可以在CornellDataset和JacquardDataset上跑，我有做過相應的訓練實驗。也可以把報錯信息發過來，我幫忙看下，我目前是覺得主要是網絡架構不同產生的報錯吧。

(ggcnn) lvze@lvze:~/Downloads/Rgbd-GG-CNN-main$ python train.py --dataset-path /home/lvze/Videos/Jacquard_Dataset_0 
INFO:root:Done
INFO:root:Loading Network...
INFO:root:Done
----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
================================================================
            Conv2d-1         [-1, 32, 200, 200]           7,808
       BatchNorm2d-2         [-1, 32, 200, 200]              64
            Conv2d-3         [-1, 16, 100, 100]          12,816
       BatchNorm2d-4         [-1, 16, 100, 100]              32
            Conv2d-5            [-1, 8, 50, 50]           1,160
       BatchNorm2d-6            [-1, 8, 50, 50]              16
            Conv2d-7         [-1, 32, 200, 200]           7,808
       BatchNorm2d-8         [-1, 32, 200, 200]              64
            Conv2d-9         [-1, 16, 100, 100]          12,816
      BatchNorm2d-10         [-1, 16, 100, 100]              32
           Conv2d-11            [-1, 8, 50, 50]           1,160
      BatchNorm2d-12            [-1, 8, 50, 50]              16
  ConvTranspose2d-13         [-1, 16, 100, 100]           2,320
  ConvTranspose2d-14         [-1, 16, 200, 200]           6,416
  ConvTranspose2d-15         [-1, 32, 601, 601]          41,504
           Conv2d-16          [-1, 1, 600, 600]             129
           Conv2d-17          [-1, 1, 600, 600]             129
           Conv2d-18          [-1, 1, 600, 600]             129
================================================================
Total params: 94,419
Trainable params: 94,419
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 4449462.89
Forward/backward pass size (MB): 147.08
Params size (MB): 0.36
Estimated Total Size (MB): 4449610.33
----------------------------------------------------------------
INFO:root:Beginning Epoch 00
Traceback (most recent call last):
  File "train.py", line 262, in <module>
    run()
  File "train.py", line 233, in run
    train_results = train(epoch, net, device, train_data, optimizer, args.batches_per_epoch)
  File "train.py", line 144, in train
    for x, y, _, _, _ in train_data:
  File "/home/lvze/anaconda3/envs/ggcnn/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/lvze/anaconda3/envs/ggcnn/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 403, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/lvze/anaconda3/envs/ggcnn/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/lvze/anaconda3/envs/ggcnn/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/lvze/Downloads/Rgbd-GG-CNN-main/utils/data/grasp_data.py", line 31, in __getitem.
File "/home/lvze/Downloads/Rgbd-GG-CNN-main/utils/data/jacquard_data.py", line 51, in get_depth
    depth_img.resize((self.output_size, self.output_size))
AttributeError: 'JacquardDataset' object has no attribute 'output_size'

你好，以上是报错信息。我在ggcnn上已经跑通了jacquard和cornell.前几天才看到您的改进代码，我看您代码里写的是针对jpg图片的数据集。我把train.py的193行train_dataset = OranDataset(args.dataset_path, start=0.0, end=args.split)改为了train_dataset = JacquardDataset(args.dataset_path, start=0.0, end=args.split).出现了以上报错。
您是觉得修改你的代码可以跑jacquard好呢，还是修改ggcnn源码，把您的框架引入进去好实现呢？本人代码能力很差。。。。。

**Comment by OranHe** [comment]
https://github.com/dougsm/ggcnn 項目中的[grasp_data.py](https://github.com/dougsm/ggcnn/blob/master/utils/data/grasp_data.py) 覆蓋到我這個項目中就可以了，您再試試，謝謝。

**Comment by zehub123** [comment]
> 你好 這個項目是在https://github.com/dougsm/ggcnn 基礎上再做修改的，可以先嘗試在ggcnn上面跑通（無需修改代碼），再引入我模型的架構可能比較好理解。我的這個項目可以在CornellDataset和JacquardDataset上跑，我有做過相應的訓練實驗。也可以把報錯信息發過來，我幫忙看下，我目前是覺得主要是網絡架構不同產生的報錯吧。


(ggcnn) lvze@lvze:~/Downloads/Rgbd-GG-CNN-main$ python train.py --dataset-path /home/lvze/Videos/Jacquard_Dataset_0 
INFO:root:Done
INFO:root:Loading Network...
INFO:root:Done
----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
================================================================
            Conv2d-1         [-1, 32, 200, 200]           7,808
       BatchNorm2d-2         [-1, 32, 200, 200]              64
            Conv2d-3         [-1, 16, 100, 100]          12,816
       BatchNorm2d-4         [-1, 16, 100, 100]              32
            Conv2d-5            [-1, 8, 50, 50]           1,160
       BatchNorm2d-6            [-1, 8, 50, 50]              16
            Conv2d-7         [-1, 32, 200, 200]           7,808
       BatchNorm2d-8         [-1, 32, 200, 200]              64
            Conv2d-9         [-1, 16, 100, 100]          12,816
      BatchNorm2d-10         [-1, 16, 100, 100]              32
           Conv2d-11            [-1, 8, 50, 50]           1,160
      BatchNorm2d-12            [-1, 8, 50, 50]              16
  ConvTranspose2d-13         [-1, 16, 100, 100]           2,320
  ConvTranspose2d-14         [-1, 16, 200, 200]           6,416
  ConvTranspose2d-15         [-1, 32, 601, 601]          41,504
           Conv2d-16          [-1, 1, 600, 600]             129
           Conv2d-17          [-1, 1, 600, 600]             129
           Conv2d-18          [-1, 1, 600, 600]             129
================================================================
Total params: 94,419
Trainable params: 94,419
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 4449462.89
Forward/backward pass size (MB): 147.08
Params size (MB): 0.36
Estimated Total Size (MB): 4449610.33
----------------------------------------------------------------
INFO:root:Beginning Epoch 00
batch_idx: 1Traceback (most recent call last):
  File "train.py", line 262, in <module>
    run()
  File "train.py", line 233, in run
    train_results = train(epoch, net, device, train_data, optimizer, args.batches_per_epoch)
  File "train.py", line 152, in train
    yc = y.to(device)  # d
AttributeError: 'list' object has no attribute 'to'
 您好，我的这个input size太大了吧，是不是不对。大佬你代码里的
xc = x.to(device)  # rgb 
yc = y.to(device)  # d 
zc = [zz.to(device) for zz in z]
比源码里的多了一个zc,这个指代的是什么哈。
您说是在源码中引入您的框架中更好实现吗？感谢感谢。

**Comment by zehub123** [comment]
> https://github.com/dougsm/ggcnn 項目中的[grasp_data.py](https://github.com/dougsm/ggcnn/blob/master/utils/data/grasp_data.py) 覆蓋到我這個項目中就可以了，您再試試，謝謝。

这个解决了。。。，我看代码也发现是grasp.py的问题。覆盖后就好了

**Comment by OranHe** [comment]
Input Size看上去很奇怪，我輸入640x480的RGBD圖的Size大概是4032.00MB。
我這邊的RGB和Depth是分別輸入網絡中的 x代表RGB y代表深度 z代表GT，GGCNN中RGBD是concat在一起（或者只用深度圖）當作x，GT當作y，如果要用我的架構，可能要在train.py、grasp.py中再做修改。

**Comment by zehub123** [comment]
> Input Size看上去很奇怪，我輸入640x480的RGBD圖的Size大概是4032.00MB。 我這邊的RGB和Depth是分別輸入網絡中的 x代表RGB y代表深度 z代表GT，GGCNN中RGBD是concat在一起（或者只用深度圖）當作x，GT當作y，如果要用我的架構，可能要在train.py、grasp.py中再做修改。

我还是在直接在您的代码上跑吧。AttributeError: 'list' object has no attribute 'to'.是说Y没有to这个属性吗。不知道怎么解决。您用自己网络跑jacquard时候，可以直接运行吗？还是需要改变数据集的格式

**Comment by OranHe** [comment]
Please leave your email here, we can solve this problem.

**Comment by zehub123** [comment]
> Please leave your email here, we can solve this problem.

897914848@qq.com

**Comment by OranHe** [comment]
已經發給您我的微信了 謝謝。

**Comment by zehub123** [comment]
> 已經發給您我的微信了 謝謝。

微信吗？我的微信号是：Deongaree7
